#macro  BONK_DRAW_POINT_RADIUS          2
#macro  BONK_DRAW_SPHERE_STEPS          24
#macro  BONK_DRAW_CYLINDER_STEPS        24
#macro  BONK_DRAW_RAY_THICKNESS         2
#macro  BONK_DRAW_RESULT_NORMAL_LENGTH  100
#macro  BONK_DRAW_PLANE_DEFAULT_COLOR   c_gray
#macro  BONK_DRAW_PLANE_SIZE            1000

#macro  BONK_DRAW_DEFAULT_DIFFUSE_COLOR  c_white
#macro  BONK_DRAW_AMBIENT_LIGHT_COLOR    c_gray
#macro  BONK_DRAW_LIGHT_COLOR            c_white
#macro  BONK_DRAW_LIGHT_DIRECTION_X      -0.4
#macro  BONK_DRAW_LIGHT_DIRECTION_Y      -0.6
#macro  BONK_DRAW_LIGHT_DIRECTION_Z      -0.8